# Generated by Django 3.2.4 on 2021-09-12 12:51

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('telephone', models.CharField(max_length=11, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_vip', models.BooleanField(default=0)),
                ('is_staff', models.BooleanField(default=False)),
                ('data_joined', models.DateTimeField(auto_now_add=True)),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=4, verbose_name='性别')),
                ('last_login', models.DateTimeField(auto_now=True, null=True, verbose_name='最后登录时间')),
                ('is_fall', models.BooleanField(default=False)),
                ('is_call', models.BooleanField(default=False)),
                ('harry_telephone', models.CharField(blank=True, max_length=11)),
                ('flag', models.BooleanField(default=0)),
                ('x', models.CharField(blank=True, max_length=100)),
                ('y', models.CharField(blank=True, max_length=100)),
                ('machineId', models.TextField(blank=True, default=0, max_length=100)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='cms.comment')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
