# Generated by Django 3.2.4 on 2021-09-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        ('mdmain', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mdauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='machine_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time', to='mdmain.machinetime'),
        ),
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_money', to='cms.vip'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
