# Generated by Django 3.2.4 on 2021-07-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('x', models.CharField(max_length=100)),
                ('y', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=11, unique=True)),
                ('sid', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'machine',
            },
        ),
    ]
