# Generated by Django 3.2.4 on 2021-09-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=0)),
                ('content', models.CharField(max_length=500)),
                ('last_login', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('addr', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=11)),
                ('qq', models.CharField(max_length=12)),
                ('kefu', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('wechat', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
